### PR TITLE
Add JSPerfProfiler

### PR DESCRIPTION
**Pull request by andykog**

### CODE REVIEW

**Comment by andykog** [comment]
@rotemmiz, @LeoNatan

**Comment by LeoNatan** [comment]
Hi,

Thanks for this PR.
Please explain what the PR does. For example, I see swizzling of setTimeout, but this is already done by the framework.
Also, is this configurable by the user? Or is this always on?

Thanks

**Comment by andykog** [comment]
This helper allows measuring all the require calls, as well as tracking all the async computations keeping the context. e. g. this allows us to calculate the performance impact on JS thread for each OA module.
Yes, this feature is optional and must be manually activated with JSPerfProfiler.attach()

**Comment by LeoNatan** [comment]
Is the reliance on all those dependencies necessary? I would like to keep this library very clean of node_modules mess. Before the PR, there are no dependencies. I would like to keep it that way.

**Comment by andykog** [comment]
I can make a separate library if you think it makes sense. @rotemmiz advised to make PR here

**Comment by andykog** [comment]
Dependencies are required for unit tests

**Comment by LeoNatan** [comment]
It's fine here, I would just like to understand if the decencies are a must. I prefer to keep the library clean. Not clean of functionality 🙂 but from node_modules.

**Comment by andykog** [comment]
Would you like to also keep it clean from unit tests? :-)

**Comment by LeoNatan** [comment]
If all those dependencies are just for Jest, then I am inclined to say yes. Is there no other way to run those tests without such a heavy baggage?

**Pull request closed without merging**
